services:
  - type: web
    name: puppeteer-service
    env: node
    buildCommand: |
      apt-get update && apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxcomposite1 \
          libxrandr2 \
          libasound2 \
          fonts-liberation
      npm install
    startCommand: node server.js
    plan: free
